spring:
  data:
    exporters:
      excel:
        formats:
        - xls
        - xlsx
        forms:
          - medicine
          - veterinary
          - flaw
      pdf:
        formats:
          - pdf